### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by MInoness** [wakeup0105/Frontend#12]
### TODO
- [x] 건강정보 클릭시 사진 + 실제 링크 넣기
- [x] 알림 모달창 버튼 수정
- [ ] 거북이 모습 변화 확인 1번 누를때마다 다음 사진으로 변경?? <-- 이건 고민좀

**Comment by MInoness** [comment]
3번째꺼 하려다가 안됨 일단 내비둬봄
